### ISSUE TITLE
Exception when Serializing Company Class

### ISSUE THREAD

**Issue by Lann094** [trbngr/infusio#20]
Sorry if this is a dumb thing to be doing, but it seemed like the best option for this project...

But I'm attempting to cache companies rather than work on them all within code, which I was hoping would be simple enough using a plain old Json Serializer. Worked perfectly for the FullContact type, but now that I'm trying to do it for Company, it's throwing this:

```
Unable to cast object of type 'Infusio.Model.CompanyAddress' to type 'Infusio.Model.Company'.
   at lambda_method(Closure , Company , Object )
   at LanguageExt.Record`1.Equals(Object obj)
   at System.Collections.Generic.ObjectEqualityComparer`1.Equals(T x, T y)
   at System.Collections.Generic.List`1.Contains(T item)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
```
I've tried forcing serializing of reference loops, since I thought that was where it was throwing it, but to no avail.

**Comment by trbngr** [comment]
Can you post a reproducible example?

**Comment by Lann094** [comment]
Ah, my apologies, looks like this is a me problem...

When setting up some test code to work out exactly where it was throwing so you could reproduce, I found it wasn't the Company class throwing it at all. I'd written my own FullCompany class that implemented Company in order for me to retrieve company tags using XML-RPC myself, since I really need them for what I'm doing. But I've apparently written that poorly, and will have to take a look at how I'm going about that.
